### ISSUE TITLE
Battery page not working

### ISSUE THREAD

**Issue by kphanipavan** [therexone/linux-mon#3]
Hello.

[Battery Page](https://user-images.githubusercontent.com/60005847/151912870-c6088ef0-f6b5-494c-86a8-6f97774e8959.png)

The battery page doesn't seem to be working properly. Other pages including the battery % on the main page works fine.

[Main Page](https://user-images.githubusercontent.com/60005847/151912974-5f9a5541-c41f-434f-8a0b-a705e771718d.png)

I am using an Acer Predator Helios 300, early 2021 model which runs Kubuntu 20.04 LTS.

I have been through python script and found you were using `psutil` for collecting data.

I ran the sensor battery command and received Null values for 2 of them.

![Screenshot_20220201_100503](https://user-images.githubusercontent.com/60005847/151913353-a07d7251-c161-4721-9739-f55f25d53622.png)

Is there any other way to obtain those values?

**Comment by therexone** [comment]
Check out the [documentation](https://psutil.readthedocs.io/en/latest/#psutil.sensors_battery) for `psutil.sensors_battery()` 

> `secsleft`: a rough approximation of how many seconds are left before the battery runs out of power. If the AC power cable is connected this is set to **psutil.POWER_TIME_UNLIMITED. If it can’t be determined it is set to psutil.POWER_TIME_UNKNOWN.**
> `power_plugged`: True if the AC power cable is connected, False if not or **None if it can’t be determined.**

I have not added a null check in case those two things are not available and that is causing the battery screen to crash.

> Is there any other way to obtain those values?

psutil uses `acpi` under the hood for linux, you can try running `acpi` and see if it shows the remaining battery time.

PS: I am not maintaining this project anymore, but you are welcome to add a PR.

**Comment by kphanipavan** [comment]
Also, may I know why random wait in server python script?

**Comment by therexone** [comment]
Added a 2 second wait to not overwhelm the websocket server

**Comment by kphanipavan** [comment]
I made some changes to the scripts, how to you make a Executable from them??

**Comment by therexone** [comment]
Use [pyinstaller](https://pyinstaller.readthedocs.io/en/stable/)

**Comment by therexone** [comment]
Fixed by #4
